### ISSUE TITLE
Hi Oliver

### ISSUE THREAD

**Issue by evangrim** [joelthelion/ploufplouf#2]
As a parent of a six year old, I've taken this to be a demo project with a child. If so, hello to Oliver from out in the world, and I hope Oliver is still learning and enjoying code. :) If not, pardon any nuisance.

And if so, I don't know how old Oliver is by now, but he might still enjoy arcade.makecode.com if you haven't found that yet (my son does, and I still do, haha). It's especially fun because you can port games to a physical handheld device, or generate QR codes to share them with friends and family.

OK, best wishes to you all!

**Comment by joelthelion** [comment]
Hi Evan,

I was actually teaching a 40-year-old about git 😄 

But thanks for the recommendation, it's very likely that my daughter will enjoy it.

Cheers!
